
spring:
  config:
    import: "optional:configserver:"

  application:
    name: ${LIBRARY-SERVICE_APPLICATION_NAME:LIBRARY-SERVICE}

  cloud:
    config:
      profile: native
      uri: http://${CONFIG_SERVER_SERVICE_NAME:127.0.0.1}:${CONFIG_SERVER_PORT:8888}



