version: '3.8'

services:

  elasticsearch:
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - ${ELASTIC_SEARCH_PORT_1}:${ELASTIC_SEARCH_PORT_1}
      - ${ELASTIC_SEARCH_PORT_2}:${ELASTIC_SEARCH_PORT_2}
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    env_file:
      - ./.env
    environment:
      - ELASTICSEARCH_URL=http://${ELASTIC_SEARCH_HOST}:${ELASTIC_SEARCH_PORT_1}
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}

  jenkins:
    env_file:
      - ./.env
    ports:
      - ${JENKINS_PORT}:${JENKINS_PORT}

  prometheus:
    env_file:
      - ./.env
    ports:
      - ${PR_PORT}:${PR_PORT}

  grafana:
    env_file:
      - ./.env
    ports:
      - ${GF_PORT}:${GF_PORT}
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}


  libraverse.accountservice.database:
    ports:
      - 5431:${ACCOUNT_SERVICE_DB_PORT}
    env_file:
      - ./.env
    expose:
      - ${ACCOUNT_SERVICE_DB_PORT}
    environment:
      - POSTGRES_USER=${ACCOUNT_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${ACCOUNT_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${ACCOUNT_SERVICE_DB_NAME}

  libraverse.libraryservice.database:
    env_file:
      - ./.env
    ports:
      - ${LIBRARY_SERVICE_DB_PORT}:${LIBRARY_SERVICE_DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${LIBRARY_SERVICE_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LIBRARY_SERVICE_DB_NAME}
      MYSQL_USER: ${LIBRARY_SERVICE_DB_USER}
      MYSQL_PASSWORD: ${LIBRARY_SERVICE_DB_PASSWORD}


  libraverse.configserver:
    container_name: ${CONFIG_SERVER_SERVICE_NAME}
    env_file:
      - ./.env
    ports:
      - ${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}

  libraverse.accountservice:
    container_name: ${ACCOUNT_SERVICE_SERVICE_NAME}
    env_file:
      - ./.env
    ports:
      - ${ACCOUNT_SERVICE_PORT}:${ACCOUNT_SERVICE_PORT}

  libraverse.apigateway:
    container_name: ${API_GATEWAY_SERVICE_NAME}
    env_file:
      - ./.env
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}

  libraverse.servicediscovery:
    container_name: ${SERVICE_DISCOVERY_SERVICE_NAME}
    env_file:
      - ./.env
    ports:
      - ${SERVICE_DISCOVERY_PORT}:${SERVICE_DISCOVERY_PORT}
