version: '3.8'

services:

  elasticsearch:
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    ports:
      - "5601:5601"

  jenkins:
    env_file:
      - ./.env
    ports:
      - "8181:8080"

  prometheus:
    env_file:
      - ./.env
    ports:
      - "9090:9090"

  grafana:
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}


  libraverse.accountservice.database:
    ports:
      - "5431:5432"
    env_file:
      - ./.env
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${ACCOUNTSERVICE_DB_USER}
      - POSTGRES_PASSWORD=${ACCOUNTSERVICE_DB_PASSWORD}
      - POSTGRES_DB=${ACCOUNTSERVICE_DB_DBNAME}

  libraverse.libraryservice.database:
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${LIBRARYSERVICE_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LIBRARYSERVICE_DB_DBNAME}
      MYSQL_USER: ${LIBRARYSERVICE_DB_USER}
      MYSQL_PASSWORD: ${LIBRARYSERVICE_DB_PASSWORD}




