
server:
  port: 8501

spring:
  application:
    name: ACCOUNT-SERVICE

  datasource:
    url: jdbc:postgresql://127.0.0.1:5431/libraverse
    username: postgres
    password: d4REn0LdCH4B

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        show_sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    user: postgres
    password: d4REn0LdCH4B
    locations: filesystem:account-service/src/main/resources/db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:8500/eureka/}
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:127.0.0.1}

