
server:
  port: ${ACCOUNT_SERVICE_PORT:8501}

spring:
  application:
    name: ${ACCOUNT_SERVICE_APPLICATION_NAME:ACCOUNT-SERVICE}

  datasource:
    url: jdbc:${ACCOUNT_SERVICE_DB:postgresql}://${ACCOUNT_SERVICE_DB_HOST:127.0.0.1}:${ACCOUNT_SERVICE_DB_PORT:5431}/${ACCOUNT_SERVICE_DB_NAME:account}
    user: ${ACCOUNT_SERVICE_DB_USER:postgres}
    password: ${ACCOUNT_SERVICE_DB_PASSWORD:d4REn0LdCH4B}

  jpa:
    properties:
      hibernate:
        dialect: ${ACCOUNT_SERVICE_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        jdbc:
          time_zone: ${JDBC_TIMEZONE:UTC}
        show_sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    user: ${ACCOUNT_SERVICE_DB_USER:postgres}
    password: ${ACCOUNT_SERVICE_DB_PASSWORD:d4REn0LdCH4B}
    locations: filesystem:${ACCOUNT_SERVICE_SERVICE_NAME:account-service}/src/main/resources/db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:127.0.0.1}:${SERVICE_DISCOVERY_PORT:8500}/eureka/
  instance:
    hostname: ${SERVICE_DISCOVERY_HOST:127.0.0.1}

