server:
  port: ${LIBRARY_SERVICE_PORT:8502}


spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://${ELASTIC_SEARCH_HOST:127.0.0.1}:${ELASTIC_SEARCH_PORT_1:9200}

  application:
    name: LIBRARY-SERVICE

  datasource:
    url: jdbc:${LIBRARY_SERVICE_DB:mysql}://${LIBRARY_SERVICE_DB_HOST:127.0.0.1}:${LIBRARY_SERVICE_DB_PORT:3306}/${LIBRARY_SERVICE_DB_NAME:librarydb}
    username: ${LIBRARY_SERVICE_DB_USER:admin}
    password: ${LIBRARY_SERVICE_DB_PASSWORD:admin}

  jpa:
    properties:
      hibernate:
        dialect: ${LIBRARY_SERVICE_JPA_DIALECT:org.hibernate.dialect.MySQL8Dialect}
        jdbc:
          time_zone: ${JDBC_TIMEZONE:UTC}
        show_sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    user: ${LIBRARY_SERVICE_DB_USER:admin}
    password: ${LIBRARY_SERVICE_DB_PASSWORD:admin}
    locations: filesystem:${LIBRARY_SERVICE_SERVICE_NAME}/src/main/resources/db/migration
    baseline-on-migrate: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:127.0.0.1}:${SERVICE_DISCOVERY_PORT:8500}/eureka/
  instance:
    hostname: ${SERVICE_DISCOVERY_HOST:127.0.0.1}
