server:
  port: ${SERVICE_DISCOVERY_PORT:8500}

spring:
  application:
    name: ${SERVICE_DISCOVERY_APPLICATION_NAME:SERVICE-DISCOVERY}

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_SERVICE_NAME:127.0.0.1}:${SERVICE_DISCOVERY_PORT:8500}/eureka/
  instance:
    hostname: ${SERVICE_DISCOVERY_SERVICE_NAME:127.0.0.1}

