server:
  port: 8500

spring:
  application:
    name: SERVICE-DISCOVERY

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:8500/eureka/}
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:127.0.0.1}

