server:
  port: ${API_GATEWAY_PORT:8088}

spring:

  application:
    name: ${API_GATEWAY_APPLICATION_NAME:API-GATEWAY}

  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: ${ACCOUNT_SERVICE_SERVICE_NAME:account-service}
          uri: lb://${ACCOUNT_SERVICE_APPLICATION_NAME:ACCOUNT-SERVICE}
          predicates:
            - Path=/account/**
          filters:
            - name: CircuitBreaker
              args:
                name: account-service-cb
                fallbackUri: forward:/fb/account
        - id: ${LIBRARY_SERVICE_SERVICE_NAME:library-service}
          uri: lb://${LIBRARY_SERVICE_APPLICATION_NAME:LIBRARY-SERVICE}
          predicates:
            - Path=/book/**
            - Path=/author/**
            - Path=/genre/**
            - Path=/language/**
            - Path=/publisher/**
          filters:
            - name: CircuitBreaker
              args:
                name: library-service-cb
                fallbackUri: forward:/fb/book


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:127.0.0.1}:${SERVICE_DISCOVERY_PORT:8500}/eureka/
  instance:
    hostname: ${SERVICE_DISCOVERY_HOST:127.0.0.1}




