server:
  port: ${SERVER_PORT:8088}

spring:

  application:
    name: API-GATEWAY

  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - name: CircuitBreaker
              args:
                name: account-service-cb
                fallbackUri: forward:/fb/account
        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/book/**
            - Path=/author/**
            - Path=/genre/**
            - Path=/language/**
            - Path=/publisher/**
          filters:
            - name: CircuitBreaker
              args:
                name: library-service-cb
                fallbackUri: forward:/fb/book


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:8500/eureka/}
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:127.0.0.1}




