DELETE FROM book_genre;
ALTER TABLE book_genre AUTO_INCREMENT = 0;

DELETE FROM book_language;
ALTER TABLE book_language AUTO_INCREMENT = 0;

DELETE FROM language;
ALTER TABLE language AUTO_INCREMENT = 0;

DELETE FROM genre;
ALTER TABLE genre AUTO_INCREMENT = 0;

DELETE FROM publisher;
ALTER TABLE publisher AUTO_INCREMENT = 0;

DELETE FROM author;
ALTER TABLE author AUTO_INCREMENT = 0;

DELETE FROM book;
ALTER TABLE book AUTO_INCREMENT = 0;

