INSERT INTO publisher (publisher_name) VALUES ('Williams, Clayton and Carr');
INSERT INTO publisher (publisher_name) VALUES ('Harvey-Walker');
INSERT INTO publisher (publisher_name) VALUES ('Weiss, Davis and Hogan');
INSERT INTO publisher (publisher_name) VALUES ('Flores Ltd');
INSERT INTO publisher (publisher_name) VALUES ('Lewis PLC');
INSERT INTO publisher (publisher_name) VALUES ('York, Butler and Anderson');
INSERT INTO publisher (publisher_name) VALUES ('Palmer Inc');
INSERT INTO publisher (publisher_name) VALUES ('Reynolds Inc');
INSERT INTO publisher (publisher_name) VALUES ('Moore-Henderson');
INSERT INTO publisher (publisher_name) VALUES ('Williams-Miller');
INSERT INTO publisher (publisher_name) VALUES ('Perez, Cox and Carlson');
INSERT INTO publisher (publisher_name) VALUES ('Oconnor-Dean');
INSERT INTO publisher (publisher_name) VALUES ('Young LLC');
INSERT INTO publisher (publisher_name) VALUES ('Baker, Kane and Leonard');
INSERT INTO publisher (publisher_name) VALUES ('Martinez-Martin');
INSERT INTO publisher (publisher_name) VALUES ('Ritter, Kent and Hamilton');
INSERT INTO publisher (publisher_name) VALUES ('Coleman LLC');
INSERT INTO publisher (publisher_name) VALUES ('Hill, Moran and Sawyer');
INSERT INTO publisher (publisher_name) VALUES ('Meyers-Adams');
INSERT INTO publisher (publisher_name) VALUES ('Ramirez LLC');
INSERT INTO publisher (publisher_name) VALUES ('Mora-Williams');
INSERT INTO publisher (publisher_name) VALUES ('Arellano, Wright and Collins');
INSERT INTO publisher (publisher_name) VALUES ('Nelson, Lewis and Brown');
INSERT INTO publisher (publisher_name) VALUES ('Dixon PLC');
INSERT INTO publisher (publisher_name) VALUES ('Bell, Garcia and Mcdaniel');
INSERT INTO publisher (publisher_name) VALUES ('Bennett PLC');
INSERT INTO publisher (publisher_name) VALUES ('Owens, Irwin and Anderson');
INSERT INTO publisher (publisher_name) VALUES ('George Ltd');
INSERT INTO publisher (publisher_name) VALUES ('Smith-Johnson');
INSERT INTO publisher (publisher_name) VALUES ('Tyler, Marks and Robertson');
INSERT INTO publisher (publisher_name) VALUES ('Blair-Martinez');
INSERT INTO publisher (publisher_name) VALUES ('Pacheco, Rogers and Nelson');
INSERT INTO publisher (publisher_name) VALUES ('Morales-Taylor');
INSERT INTO publisher (publisher_name) VALUES ('Mcdaniel-Miller');
INSERT INTO publisher (publisher_name) VALUES ('Owen-Baker');
INSERT INTO publisher (publisher_name) VALUES ('Rangel-Morse');
INSERT INTO publisher (publisher_name) VALUES ('Lewis-Smith');
INSERT INTO publisher (publisher_name) VALUES ('Gonzalez and Sons');
INSERT INTO publisher (publisher_name) VALUES ('Cook PLC');
INSERT INTO publisher (publisher_name) VALUES ('Rodriguez-Lewis');
INSERT INTO publisher (publisher_name) VALUES ('Scott Ltd');
INSERT INTO publisher (publisher_name) VALUES ('Jimenez, Downs and Gonzalez');
INSERT INTO publisher (publisher_name) VALUES ('Williams-Graves');
INSERT INTO publisher (publisher_name) VALUES ('West-Richardson');
INSERT INTO publisher (publisher_name) VALUES ('Cummings LLC');
INSERT INTO publisher (publisher_name) VALUES ('Flowers-Gregory');
INSERT INTO publisher (publisher_name) VALUES ('Davis, Sanders and Carroll');
INSERT INTO publisher (publisher_name) VALUES ('Thompson, Delgado and Lewis');
INSERT INTO publisher (publisher_name) VALUES ('Owen PLC');
INSERT INTO publisher (publisher_name) VALUES ('Arroyo Group');
