INSERT INTO genre (genre_name) VALUES ('Fantasy');
INSERT INTO genre (genre_name) VALUES ('Science Fiction');
INSERT INTO genre (genre_name) VALUES ('Romance');
INSERT INTO genre (genre_name) VALUES ('Mystery');
INSERT INTO genre (genre_name) VALUES ('Thriller');
INSERT INTO genre (genre_name) VALUES ('Horror');
INSERT INTO genre (genre_name) VALUES ('Historical Fiction');
INSERT INTO genre (genre_name) VALUES ('Non-fiction');
INSERT INTO genre (genre_name) VALUES ('Biography');
INSERT INTO genre (genre_name) VALUES ('Memoir');
INSERT INTO genre (genre_name) VALUES ('Young Adult');
INSERT INTO genre (genre_name) VALUES ('Children');
