
spring:
  config:
    import: "optional:configserver:"

  application:
    name: ACCOUNT-SERVICE

  cloud:
    config:
      profile: native
      uri: ${CONFIG_SERVER_URL:http://127.0.0.1:8888}





