server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: ${CONFIG_SERVER_APPLICATION_NAME:CONFIG-SERVER}
  profiles:
    active: composite

  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/settings